Scripts cleanup

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,27 +1,25 @@
 #!/bin/bash
+app="searx"
+
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -e
+
+# Source app helpers
+. /usr/share/yunohost/helpers
 
 # Retrieve arguments
-domain=$1
-path=$2
-is_public=$3
+domain=$YNH_APP_ARG_DOMAIN
+path=$YNH_APP_ARG_PATH
+is_public=$YNH_APP_ARG_IS_PUBLIC
+
+# Remove trailing slash to path
+path=${path%/}
+#force location to be / or /foo
+location=${path:-/}
 
 # Check domain/path availability
-sudo yunohost app checkurl $domain$path -a searx
-if [[ ! $? -eq 0 ]]; then
-	exit 1
-fi
-
-# Path need a trailing slash, and location does not.
-# See conf/nginx.conf* usage
-location=$path
-if [[ ! $path == */ ]]; then
-    # no trailing slash, so add it
-    path=$path/
-fi
-if [[ ! "$location" == "/" ]]; then
-    # remove possible trailing slash
-    location=${location%/}
-fi
+sudo yunohost app checkurl $domain$path -a $app \
+    || (echo "Path not available: $domain$path" && exit 1)
 
 # Save specific settings
 sudo yunohost app setting searx is_public -v $is_public
@@ -46,7 +44,7 @@ then
 	sudo swapon $tmp_swap_file
 fi
 
-final_path=/opt/yunohost/searx
+final_path=/opt/yunohost/$app
 
 # Init virtualenv
 if [ ! -d $final_path ];
@@ -79,17 +77,17 @@ sudo useradd searx -d $final_path
 sudo chown searx:searx -R $final_path
 
 # Copy uwsgi config
-sudo cp ../conf/searx.ini /etc/uwsgi/apps-available/
-sudo ln -s /etc/uwsgi/apps-available/searx.ini /etc/uwsgi/apps-enabled/
+sudo cp ../conf/searx.ini /etc/uwsgi/apps-available/$app.ini
+sudo ln -s /etc/uwsgi/apps-available/searx.ini /etc/uwsgi/apps-enabled/$app.ini
 
 # Modify Nginx configuration file and copy it to Nginx conf directory
 sed -i "s@YNH_WWW_LOCATION@$location@g" ../conf/nginx.conf*
 sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf*
 if [ "$path" != "/" ];
 then
-	sudo cp ../conf/nginx.conf-noroot /etc/nginx/conf.d/$domain.d/searx.conf
+	sudo cp ../conf/nginx.conf-noroot /etc/nginx/conf.d/$domain.d/$app.conf
 else
-	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/searx.conf
+	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 fi
 
 # Fix permission
@@ -99,11 +97,10 @@ fi
 ## Reload Nginx and regenerate SSOwat conf
 sudo service nginx reload
 sudo service uwsgi restart
-sudo yunohost service add uwsgi -l /var/log/uwsgi/app/searx.log
+sudo yunohost service add uwsgi -l /var/log/uwsgi/app/$app.log
 
 if [ "$is_public" = "Yes" ];
 then
-	sudo yunohost app setting searx unprotected_uris -v "/"
+	sudo yunohost app setting $app unprotected_uris -v "/"
 fi
-sudo yunohost app ssowatconf
 
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,21 +1,21 @@
 #!/bin/bash
+app="searx"
+
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -e
+
+# Source app helpers
+. /usr/share/yunohost/helpers
 
 # Retrieve arguments
-domain=$(sudo yunohost app setting searx domain)
-path=$(sudo yunohost app setting searx path)
-is_public=$(sudo yunohost app setting searx is_public)
+domain=$(ynh_app_setting_get "$app" domain)
+path=$(ynh_app_setting_get "$app" path)
+is_public=$(ynh_app_setting_get "$app" is_public)
 
-# Path need a trailing slash, and location does not.
-# See conf/nginx.conf usage
-location=$path
-if [[ ! $path == */ ]]; then
-    # no trailing slash, so add it
-    path=$path/
-fi
-if [[ ! "$location" == "/" ]]; then
-    # remove possible trailing slash
-    location=${location%/}
-fi
+# Remove trailing slash to path
+path=${path%/}
+#force location to be / or /foo
+location=${path:-/}
 
 # Check depends installation
 sudo apt-get install git build-essential libxslt-dev python-dev python-virtualenv python-pybabel zlib1g-dev libffi-dev libssl-dev python-lxml uwsgi uwsgi-plugin-python -y
@@ -36,7 +36,7 @@ then
 	sudo swapon $tmp_swap_file
 fi
 
-final_path=/opt/yunohost/searx
+final_path=/opt/yunohost/$app
 sudo cp -r ../sources/* $final_path
 sudo bash -c "source $final_path/bin/activate && pip install -r $final_path/requirements-ynh.txt --upgrade"
 
@@ -45,12 +45,6 @@ if [[ -v "$tmp_swap_file" ]];
 then
     sudo swapoff $tmp_swap_file
     sudo rm -f $tmp_swap_file
-fi
-
-# Remove trailing "/" for next commands if installing on a subpath
-if [ "$path" != "/" ];
-then
-        path=${path%/}
 fi
 
 #Configuration Searx
@@ -70,30 +64,29 @@ fi
 sudo chown searx:searx -R $final_path
 
 # Copy uwsgi config
-sudo cp ../conf/searx.ini /etc/uwsgi/apps-available/
+sudo cp ../conf/searx.ini /etc/uwsgi/apps-available/$app.ini
 
 # Modify Nginx configuration file and copy it to Nginx conf directory
 sed -i "s@YNH_WWW_LOCATION@$location@g" ../conf/nginx.conf*
 sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf*
 if [ "$path" != "/" ];
 then
-    sudo cp ../conf/nginx.conf-noroot /etc/nginx/conf.d/$domain.d/searx.conf
+    sudo cp ../conf/nginx.conf-noroot /etc/nginx/conf.d/$domain.d/$app.conf
 else
-    sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/searx.conf
+    sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 fi
 
 # Fix permission
 #sudo find $final_path/ -type d -exec chmod 2755 {} \;
 #sudo find $final_path/ -type f -exec chmod g+r,o+r {} \;
 
-## Reload Nginx and regenerate SSOwat conf
-sudo service nginx reload
-sudo service uwsgi restart
-
 if [ "$is_public" = "Yes" ];
 then
     sudo yunohost app setting searx skipped_uris -d
     sudo yunohost app setting searx unprotected_uris -v "/"
 fi
-sudo yunohost app ssowatconf
+
+## Reload services
+sudo service nginx reload
+sudo service uwsgi restart
 
